services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-devops-cicd
    environment:
      APP_VERSION: ${APP_VERSION:-0.1.0}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "8000:8000"
